services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
  mongodb:
    image: mongo
    command: mongod --port 27018
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27018:27018
    volumes:
      - /var/lib/mongodb/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  # auction-svc:
  #   image: jinyoung777/auction-svc:latest
  #   build:
  #     context: .
  #     dockerfile: src/AuctionService/Dockerfile
  #   environment:
  #     - ASPNETCORE_ENVIRONEMNT=Development
  #     - ASPNETCORE_URLS=http://+:80
  #     - RabbitMq__Host=rabbitmq
  #     - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=auctions
  #     - IdentityServiceUrl=http://identity-svc
  #   ports:
  #     - 7001:80
  #   depends_on:
  #     - postgres
  #     - rabbitmq
  # search-svc:
  #   image: jinyoung777/search-svc:latest
  #   build:
  #     context: .
  #     dockerfile: src/SearchService/Dockerfile
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:80
  #     - RabbitMq__Host=rabbitmq
  #     - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@mongodb:27018
  #     - AuctionServiceUrl=http://auction-svc
  #   ports:
  #     - 7002:80
  #   depends_on:
  #     - mongodb
  #     - rabbitmq
  # identity-svc:
  #   image: jinyoung777/identity-svc:latest
  #   build:
  #     context: .
  #     dockerfile: src/IdentityService/Dockerfile
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Docker
  #     - ASPNETCORE_URLS=http://+:80
  #     - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=identity
  #   ports:
  #     - 5000:80
  #   depends_on:
  #     - postgres
